development:
  adapter: mysql2
  encoding: utf8
  database: news
  username: root
  password: "123456"
  host: localhost
test: 
  adapter: mysql2
  encoding: utf8 
  database: login_test 
  host: localhost 
  username: root 
  password: "123456"
production: 
  adapter: mysql2
  encoding: utf8
  database: news
  username: root
  password: "123456"
  host: localhost